#!/bin/sh
echo "this is to move files"
echo pwd
cp /home/naheda/source/file1.txt /home/naheda/destination
mv /home/naheda/destination/file1.txt /home/naheda/third_folder
# FILE EDITED
echo "This is modified one"
